version: "3.7"
services:
        mysql:
                image: callumgoodley/trio-task_mysql
                build: ./db 
                environment:
                           MYSQL_USER: ${DB_USERNAME}
                           MYSQL_PASSWORD: ${DB_PASSWORD}
                           MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                           MYSQL_DATABASE: flask-db
                ports:
                        - target: 3306
                          published: 3306
                          protocol: tcp

        flask-app:
                image: callumgoodley/trio-task_flask-app
                build: ./flask-app
                environment:
                          DB_USERNAME: ${DB_USERNAME} 
                          DB_PASSWORD: ${DB_PASSWORD}
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
                depends_on:
                        - mysql
        nginx:
                image: nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp

                depends_on: 
                        - flask-app
                volumes: 
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
